### ISSUE TITLE
Improving for loop

### ISSUE THREAD

**Issue by ravening** [philipperemy/Order-Book-Matching-Engine#1]
In the `receiveOrder` function, you dont need to go over all the ask and bid orders right? Once the quantity is 0, you can exit the for loop.

Lets say there are 1million ask orders and a new bid order comes for just 1 quantity with sutiable price. Then even after satisfying the order, you will still iterate 1million - 1 times which is not needed

**Comment by philipperemy** [comment]
Right! Good catch I updated it.
