### ISSUE TITLE
Issue in buying and selling order

### ISSUE THREAD

**Issue by ravening** [philipperemy/Order-Book-Matching-Engine#2]
If there are 3 bid orders
```
<99.95, 100>
<99.90, 50>
<99.85,50>
``` 
and 3 ask orders
```
<100.00, 1000>
<100.05, 50>
<100.10, 90>
```

if a new bid(buy) order comes for `<99.97, 1>`  then
```
for (double ask_price : ask_prices_list) {
	if (quantity > 0 && price >= ask_price) {
```

will be false since price(99.97) is not greater than ask_price(100.00) and the order is never executed.
This is a bug. i guess same issue with sell order as well

**Comment by philipperemy** [comment]
I think it's a correct behavior since a buy order at 99.97 will be resting in the order book because the best ask price is 100.00.

**Comment by philipperemy** [comment]
But I get what you mean. I wrote this lib a long time ago and I had a method `receiveOrder` to be aggressive. I'm going to revamp it a bit.

**Comment by philipperemy** [comment]
I updated the code thank you!
